version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - 5173:5173
      - 4173:4173
      - 3000:3000
